export const PERMISSIONS = {
  VIEW_MEMBER_AREA: "VIEW_MEMBER_AREA",

  VOTE: "VOTE",
  VIEW_HISTORY: "VIEW_HISTORY",
  VIEW_RESULTS: "VIEW_RESULTS",

  POLL_CREATE: "POLL_CREATE",
  POLL_EDIT: "POLL_EDIT",
  POLL_DELETE: "POLL_DELETE",
  POLL_PUBLISH: "POLL_PUBLISH",
  POLL_CANCEL: "POLL_CANCEL",
  POLL_OPTIONS_MANAGE: "POLL_OPTIONS_MANAGE",
  ADMIN_DASHBOARD_VIEW: "ADMIN_DASHBOARD_VIEW",
  POLL_VIEW_MANAGEMENT: "POLL_VIEW_MANAGEMENT",
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",
  NOTIFICATION_RETRY: "NOTIFICATION_RETRY",

  USER_MANAGE: "USER_MANAGE",
  ROLE_MANAGE: "ROLE_MANAGE",
};
export const ROLE_PERMISSIONS = {
  User: [
    PERMISSIONS.VIEW_MEMBER_AREA,
    PERMISSIONS.VOTE,
    PERMISSIONS.VIEW_HISTORY,
    PERMISSIONS.VIEW_RESULTS,
  ],

  Editor: [
    PERMISSIONS.VIEW_MEMBER_AREA,
    PERMISSIONS.VOTE,
    PERMISSIONS.VIEW_HISTORY,
    PERMISSIONS.VIEW_RESULTS,

    PERMISSIONS.POLL_CREATE,
    PERMISSIONS.POLL_EDIT,
    PERMISSIONS.POLL_DELETE,
    PERMISSIONS.POLL_PUBLISH,
    PERMISSIONS.POLL_CANCEL,
    PERMISSIONS.POLL_OPTIONS_MANAGE,

    PERMISSIONS.NOTIFICATION_RETRY,
    PERMISSIONS.ADMIN_DASHBOARD_VIEW,
    PERMISSIONS.POLL_VIEW_MANAGEMENT,
  ],

  Admin: [
    PERMISSIONS.VIEW_MEMBER_AREA,
    PERMISSIONS.VOTE,
    PERMISSIONS.VIEW_HISTORY,
    PERMISSIONS.VIEW_RESULTS,

    PERMISSIONS.POLL_CREATE,
    PERMISSIONS.POLL_EDIT,
    PERMISSIONS.POLL_DELETE,
    PERMISSIONS.POLL_PUBLISH,
    PERMISSIONS.POLL_CANCEL,
    PERMISSIONS.POLL_OPTIONS_MANAGE,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.NOTIFICATION_RETRY,

    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.ADMIN_DASHBOARD_VIEW,
    PERMISSIONS.POLL_VIEW_MANAGEMENT,
  ],
};
